name: New issue
on:
  issues:
    types:
    - opened
jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
    - uses: alex-page/github-project-automation-plus@v0.1.0
      with:
        project: test
        column: To do
        repo-token: ${{ secrets.GITHUB_TOKEN }}

